server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # backend proxy (your case)
    location /api/ {
        proxy_pass http://192.168.64.3:8080;
    }
}